In [4]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

from sklearn.metrics import confusion_matrix,accuracy_score,recall_score,precision_score,f1_score
from sklearn.dummy import DummyClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import Perceptron
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score

import os

path=r'C:\Users\HP\Desktop\U\2 Semestre 2022\ML\Talleres\ml-fintech\\'

In [5]:
#descripción columnas
df_dc=pd.read_csv("columns_description.csv")
df_dc

,Unnamed: 0,Table,Row,Description,Special
0,0,solicitud_{train/test}.csv,SK_ID_CURR,ID of loan in our sample,NaN
1,1,solicitud_{train/test}.csv,TARGET,Target variable (1 - client with payment diffi...,NaN
2,2,solicitud_{train/test}.csv,NAME_CONTRACT_TYPE,Identification if loan is cash or revolving,NaN
3,3,solicitud_{train/test}.csv,CODE_GENDER,Gender of the client,NaN
4,4,solicitud_{train/test}.csv,FLAG_OWN_CAR,Flag if the client owns a car,NaN
...,...,...,...,...,...
160,160,tarjeta_credito_movimientos.csv.csv,CNT_DRAWINGS_POS_CURRENT,Number of drawings for goods during this month...,NaN
161,161,tarjeta_credito_movimientos.csv.csv,CNT_INSTALMENT_MATURE_CUM,Number of paid installments on the previous cr...,NaN
162,162,tarjeta_credito_movimientos.csv.csv,NAME_CONTRACT_STATUS,"Contract status (active signed,...) on the pre...",NaN
163,163,tarjeta_credito_movimientos.csv.csv,SK_DPD,DPD (Days past due) during the month on the pr...,NaN
164,164,tarjeta_credito_movimientos.csv.csv,SK_DPD_DEF,DPD (Days past due) during the month with tole...,NaN

In [6]:
#historial_prestamos
df_hp=pd.read_csv("historial_prestamos.csv")
df_hp

,Unnamed: 0.1,Unnamed: 0,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
0,0,0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.00,0.0,NaN,0.0,Consumer credit,-131,NaN
1,1,1,215354,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,225000.00,171342.0,NaN,0.0,Credit card,-20,NaN
2,2,2,215354,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,464323.50,NaN,NaN,0.0,Consumer credit,-16,NaN
3,3,3,215354,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,90000.00,NaN,NaN,0.0,Credit card,-16,NaN
4,4,4,215354,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,2700000.00,NaN,NaN,0.0,Consumer credit,-21,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1025646,1465316,1716419,352790,5057718,Closed,currency 1,-1808,0,-1596.0,-1625.0,8100.0,0,28248.84,0.0,0.0,0.0,Consumer credit,-1625,NaN
1025647,1465317,1716420,352790,5057725,Closed,currency 1,-99,0,-83.0,-98.0,NaN,0,27000.00,0.0,0.0,0.0,Consumer credit,-18,NaN
1025648,1465320,1716423,259355,5057750,Active,currency 1,-44,0,-30.0,NaN,0.0,0,11250.00,11250.0,0.0,0.0,Microloan,-19,NaN
1025649,1465323,1716426,246829,5057770,Closed,currency 1,-1878,0,-1513.0,-1513.0,NaN,0,36000.00,0.0,0.0,0.0,Consumer credit,-1508,NaN
1025650,1465324,1716427,246829,5057778,Closed,currency 1,-463,0,NaN,-387.0,NaN,0,22500.00,0.0,NaN,0.0,Microloan,-387,NaN

In [7]:
df_hp.isna().sum()

Unnamed: 0.1                   0
Unnamed: 0                     0
SK_ID_CURR                     0
SK_ID_BUREAU                   0
CREDIT_ACTIVE                  0
CREDIT_CURRENCY                0
DAYS_CREDIT                    0
CREDIT_DAY_OVERDUE             0
DAYS_CREDIT_ENDDATE        61977
DAYS_ENDDATE_FACT         381761
AMT_CREDIT_MAX_OVERDUE    663895
CNT_CREDIT_PROLONG             0
AMT_CREDIT_SUM                 2
AMT_CREDIT_SUM_DEBT       156515
AMT_CREDIT_SUM_LIMIT      342424
AMT_CREDIT_SUM_OVERDUE         0
CREDIT_TYPE                    0
DAYS_CREDIT_UPDATE             0
AMT_ANNUITY               791360
dtype: int64

In [8]:
#historial_prestamos_movimientos
df_hpm=pd.read_csv("historial_prestamos_movimientos.csv")
df_hpm

          Unnamed: 0.1  Unnamed: 0  SK_ID_BUREAU  MONTHS_BALANCE STATUS
0                    0           0       5715448               0      C
1                    1           1       5715448              -1      C
2                    2           2       5715448              -2      C
3                    3           3       5715448              -3      C
4                    4           4       5715448              -4      C
...                ...         ...           ...             ...    ...
10314562      14701607    27299920       5041336             -47      X
10314563      14701608    27299921       5041336             -48      X
10314564      14701609    27299922       5041336             -49      X
10314565      14701610    27299923       5041336             -50      X
10314566      14701611    27299924       5041336             -51      X

[10314567 rows x 5 columns]

In [9]:
#df_hpydf_hpm=df_hp.merge(df_hpm, how='outer', on='SK_ID_BUREAU')
#df_hpydf_hpm

In [10]:
df_hpm.isna().sum()

Unnamed: 0.1      0
Unnamed: 0        0
SK_ID_BUREAU      0
MONTHS_BALANCE    0
STATUS            0
dtype: int64

In [11]:
#tarjeta credito movimientos
df_tcm=pd.read_csv("tarjeta_credito_movimientos.csv")
df_tcm

,Unnamed: 0.1,Unnamed: 0,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,...,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,0,1,2582071,363914,-1,63975.555,45000,2250.0,2250.000,0.0,...,64875.555,64875.555,1.0,1,0.0,0.0,69.0,Active,0,0
1,1,3,1389973,337855,-4,236572.110,225000,2250.0,2250.000,0.0,...,233048.970,233048.970,1.0,1,0.0,0.0,10.0,Active,0,0
2,2,4,1891521,126868,-1,453919.455,450000,0.0,11547.000,0.0,...,453919.455,453919.455,0.0,1,0.0,1.0,101.0,Active,0,0
3,3,8,2181852,367360,-4,291543.075,292500,90000.0,289339.425,0.0,...,286831.575,286831.575,3.0,8,0.0,5.0,3.0,Active,0,0
4,4,9,1235299,203885,-5,201261.195,225000,76500.0,111026.700,0.0,...,197224.695,197224.695,3.0,9,0.0,6.0,38.0,Active,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2267046,3227959,3840306,1410474,255737,-13,0.000,180000,NaN,0.000,NaN,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
2267047,3227960,3840307,1036507,328243,-9,0.000,45000,NaN,0.000,NaN,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
2267048,3227961,3840308,1714892,347207,-9,0.000,45000,0.0,0.000,0.0,...,0.000,0.000,0.0,0,0.0,0.0,23.0,Active,0,0
2267049,3227962,3840309,1302323,215757,-9,275784.975,585000,270000.0,270000.000,0.0,...,273093.975,273093.975,2.0,2,0.0,0.0,18.0,Active,0,0
2267050,3227964,3840311,2411345,236760,-10,0.000,157500,0.0,0.000,0.0,...,0.000,0.000,0.0,0,0.0,0.0,21.0,Completed,0,0

In [12]:
#df_hpydf_hpmydf_tcm=df_hpydf_hpm.merge(df_tcm, how='left', on='SK_ID_CURR')

In [13]:
#solicitudes test
df_stest=pd.read_csv("solicitudes_test.csv")
df_stest

,Unnamed: 0,SK_ID_CURR,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,0,251482,Cash loans,M,Y,Y,1,247500.0,338832.0,17869.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
1,1,152322,Cash loans,F,Y,Y,0,157500.0,566055.0,16681.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,2.0
2,2,213864,Cash loans,F,Y,N,0,225000.0,1024740.0,52452.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
3,3,149195,Cash loans,M,Y,Y,1,90000.0,1078200.0,31653.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,215443,Cash loans,F,N,Y,0,81000.0,269550.0,12964.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64573,64573,449354,Cash loans,F,N,Y,0,157500.0,808650.0,29709.0,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,2.0
64574,64574,118433,Cash loans,M,N,Y,0,540000.0,306000.0,11664.0,...,0,0,0,0,0.0,0.0,1.0,0.0,0.0,2.0
64575,64575,177671,Cash loans,F,N,N,0,112500.0,454500.0,19107.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
64576,64576,449847,Cash loans,F,N,Y,0,112500.0,805882.5,25434.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,3.0
64577,64577,390409,Cash loans,M,Y,Y,0,225000.0,640080.0,31261.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0

In [14]:
df_stest.isna().sum()

Unnamed: 0                       0
SK_ID_CURR                       0
NAME_CONTRACT_TYPE               0
CODE_GENDER                      0
FLAG_OWN_CAR                     0
                              ...
AMT_REQ_CREDIT_BUREAU_DAY     8756
AMT_REQ_CREDIT_BUREAU_WEEK    8756
AMT_REQ_CREDIT_BUREAU_MON     8756
AMT_REQ_CREDIT_BUREAU_QRT     8756
AMT_REQ_CREDIT_BUREAU_YEAR    8756
Length: 122, dtype: int64

In [15]:
#solicitudes train
df_strain=pd.read_csv("solicitudes_train.csv")
df_strain

,Unnamed: 0,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,0,331475,0,Cash loans,F,Y,Y,0,135000.0,835380.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,366488,0,Cash loans,F,N,Y,0,103500.0,659533.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
2,2,444791,0,Cash loans,F,N,Y,0,135000.0,219042.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
3,3,112960,0,Revolving loans,F,N,Y,0,67500.0,675000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,9.0
4,4,418735,0,Revolving loans,F,N,Y,0,315000.0,900000.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150674,150674,244356,0,Cash loans,M,N,Y,0,112500.0,112068.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
150675,150675,213955,0,Cash loans,F,N,Y,0,135000.0,781920.0,...,0,0,0,0,0.0,0.0,0.0,1.0,1.0,2.0
150676,150676,376877,0,Revolving loans,F,N,Y,0,135000.0,202500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
150677,150677,246747,0,Cash loans,F,N,N,1,135000.0,508495.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
150678,150678,224980,0,Revolving loans,F,N,Y,1,67500.0,180000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
#df_strain2=df_strain.merge(df_tcm, how='left', on='SK_ID_CURR')

In [17]:
#df_strain1=df_strain2.merge(df_hp, how='left', on='SK_ID_CURR')

In [18]:
df_train=df_strain.iloc[:,1:]
df_train=df_train.drop(columns='SK_ID_CURR')#,'TARGET'])
df_train

,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,0,Cash loans,F,Y,Y,0,135000.0,835380.0,30955.5,675000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1,0,Cash loans,F,N,Y,0,103500.0,659533.5,26284.5,589500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
2,0,Cash loans,F,N,Y,0,135000.0,219042.0,23130.0,193500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
3,0,Revolving loans,F,N,Y,0,67500.0,675000.0,33750.0,675000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,9.0
4,0,Revolving loans,F,N,Y,0,315000.0,900000.0,45000.0,900000.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150674,0,Cash loans,M,N,Y,0,112500.0,112068.0,11610.0,99000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
150675,0,Cash loans,F,N,Y,0,135000.0,781920.0,32998.5,675000.0,...,0,0,0,0,0.0,0.0,0.0,1.0,1.0,2.0
150676,0,Revolving loans,F,N,Y,0,135000.0,202500.0,10125.0,202500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
150677,0,Cash loans,F,N,N,1,135000.0,508495.5,21541.5,454500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
150678,0,Revolving loans,F,N,Y,1,67500.0,180000.0,9000.0,180000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
categorical = [var for var in df_train.columns if df_train[var].dtype=='O']
categorical

['NAME_CONTRACT_TYPE',
 'CODE_GENDER',
 'FLAG_OWN_CAR',
 'FLAG_OWN_REALTY',
 'NAME_TYPE_SUITE',
 'NAME_INCOME_TYPE',
 'NAME_EDUCATION_TYPE',
 'NAME_FAMILY_STATUS',
 'NAME_HOUSING_TYPE',
 'OCCUPATION_TYPE',
 'WEEKDAY_APPR_PROCESS_START',
 'ORGANIZATION_TYPE',
 'FONDKAPREMONT_MODE',
 'HOUSETYPE_MODE',
 'WALLSMATERIAL_MODE',
 'EMERGENCYSTATE_MODE']

In [20]:
numerical = [var for var in df_train.columns if df_train[var].dtype!='O']
numerical

['TARGET',
 'CNT_CHILDREN',
 'AMT_INCOME_TOTAL',
 'AMT_CREDIT',
 'AMT_ANNUITY',
 'AMT_GOODS_PRICE',
 'REGION_POPULATION_RELATIVE',
 'DAYS_BIRTH',
 'DAYS_EMPLOYED',
 'DAYS_REGISTRATION',
 'DAYS_ID_PUBLISH',
 'OWN_CAR_AGE',
 'FLAG_MOBIL',
 'FLAG_EMP_PHONE',
 'FLAG_WORK_PHONE',
 'FLAG_CONT_MOBILE',
 'FLAG_PHONE',
 'FLAG_EMAIL',
 'CNT_FAM_MEMBERS',
 'REGION_RATING_CLIENT',
 'REGION_RATING_CLIENT_W_CITY',
 'HOUR_APPR_PROCESS_START',
 'REG_REGION_NOT_LIVE_REGION',
 'REG_REGION_NOT_WORK_REGION',
 'LIVE_REGION_NOT_WORK_REGION',
 'REG_CITY_NOT_LIVE_CITY',
 'REG_CITY_NOT_WORK_CITY',
 'LIVE_CITY_NOT_WORK_CITY',
 'EXT_SOURCE_1',
 'EXT_SOURCE_2',
 'EXT_SOURCE_3',
 'APARTMENTS_AVG',
 'BASEMENTAREA_AVG',
 'YEARS_BEGINEXPLUATATION_AVG',
 'YEARS_BUILD_AVG',
 'COMMONAREA_AVG',
 'ELEVATORS_AVG',
 'ENTRANCES_AVG',
 'FLOORSMAX_AVG',
 'FLOORSMIN_AVG',
 'LANDAREA_AVG',
 'LIVINGAPARTMENTS_AVG',
 'LIVINGAREA_AVG',
 'NONLIVINGAPARTMENTS_AVG',
 'NONLIVINGAREA_AVG',
 'APARTMENTS_MODE',
 'BASEMENTAREA_MODE',
 'YEARS_BEGINEXPLUATATION_MODE',
 'YEARS_BUILD_MODE',
 'COMMONAREA_MODE',
 'ELEVATORS_MODE',
 'ENTRANCES_MODE',
 'FLOORSMAX_MODE',
 'FLOORSMIN_MODE',
 'LANDAREA_MODE',
 'LIVINGAPARTMENTS_MODE',
 'LIVINGAREA_MODE',
 'NONLIVINGAPARTMENTS_MODE',
 'NONLIVINGAREA_MODE',
 'APARTMENTS_MEDI',
 'BASEMENTAREA_MEDI',
 'YEARS_BEGINEXPLUATATION_MEDI',
 'YEARS_BUILD_MEDI',
 'COMMONAREA_MEDI',
 'ELEVATORS_MEDI',
 'ENTRANCES_MEDI',
 'FLOORSMAX_MEDI',
 'FLOORSMIN_MEDI',
 'LANDAREA_MEDI',
 'LIVINGAPARTMENTS_MEDI',
 'LIVINGAREA_MEDI',
 'NONLIVINGAPARTMENTS_MEDI',
 'NONLIVINGAREA_MEDI',
 'TOTALAREA_MODE',
 'OBS_30_CNT_SOCIAL_CIRCLE',
 'DEF_30_CNT_SOCIAL_CIRCLE',
 'OBS_60_CNT_SOCIAL_CIRCLE',
 'DEF_60_CNT_SOCIAL_CIRCLE',
 'DAYS_LAST_PHONE_CHANGE',
 'FLAG_DOCUMENT_2',
 'FLAG_DOCUMENT_3',
 'FLAG_DOCUMENT_4',
 'FLAG_DOCUMENT_5',
 'FLAG_DOCUMENT_6',
 'FLAG_DOCUMENT_7',
 'FLAG_DOCUMENT_8',
 'FLAG_DOCUMENT_9',
 'FLAG_DOCUMENT_10',
 'FLAG_DOCUMENT_11',
 'FLAG_DOCUMENT_12',
 'FLAG_DOCUMENT_13',
 'FLAG_DOCUMENT_14',
 'FLAG_DOCUMENT_15',
 'FLAG_DOCUMENT_16',
 'FLAG_DOCUMENT_17',
 'FLAG_DOCUMENT_18',
 'FLAG_DOCUMENT_19',
 'FLAG_DOCUMENT_20',
 'FLAG_DOCUMENT_21',
 'AMT_REQ_CREDIT_BUREAU_HOUR',
 'AMT_REQ_CREDIT_BUREAU_DAY',
 'AMT_REQ_CREDIT_BUREAU_WEEK',
 'AMT_REQ_CREDIT_BUREAU_MON',
 'AMT_REQ_CREDIT_BUREAU_QRT',
 'AMT_REQ_CREDIT_BUREAU_YEAR']

In [21]:
train_c=df_train[categorical]
train_n=df_train[numerical]

In [22]:
train_c

,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,OCCUPATION_TYPE,WEEKDAY_APPR_PROCESS_START,ORGANIZATION_TYPE,FONDKAPREMONT_MODE,HOUSETYPE_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE
0,Cash loans,F,Y,Y,Unaccompanied,Pensioner,Secondary / secondary special,Married,House / apartment,NaN,FRIDAY,XNA,NaN,NaN,NaN,NaN
1,Cash loans,F,N,Y,Family,Pensioner,Secondary / secondary special,Married,House / apartment,NaN,WEDNESDAY,XNA,NaN,NaN,NaN,NaN
2,Cash loans,F,N,Y,Unaccompanied,Working,Incomplete higher,Single / not married,House / apartment,NaN,MONDAY,Business Entity Type 3,NaN,NaN,NaN,No
3,Revolving loans,F,N,Y,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,Laborers,MONDAY,Restaurant,NaN,block of flats,Block,No
4,Revolving loans,F,N,Y,Unaccompanied,Pensioner,Higher education,Single / not married,House / apartment,NaN,FRIDAY,XNA,NaN,block of flats,"Stone, brick",No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150674,Cash loans,M,N,Y,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,Laborers,SATURDAY,Business Entity Type 3,NaN,NaN,NaN,NaN
150675,Cash loans,F,N,Y,Unaccompanied,State servant,Secondary / secondary special,Married,House / apartment,NaN,FRIDAY,Medicine,NaN,block of flats,"Stone, brick",No
150676,Revolving loans,F,N,Y,Family,Pensioner,Secondary / secondary special,Married,House / apartment,NaN,MONDAY,XNA,NaN,NaN,NaN,NaN
150677,Cash loans,F,N,N,Unaccompanied,Working,Higher education,Married,House / apartment,Core staff,MONDAY,Government,NaN,block of flats,Panel,No
150678,Revolving loans,F,N,Y,Family,Working,Secondary / secondary special,Separated,House / apartment,Laborers,SUNDAY,Industry: type 11,reg oper account,block of flats,"Stone, brick",No

In [23]:
train_c.isna().sum()

NAME_CONTRACT_TYPE                 0
CODE_GENDER                        0
FLAG_OWN_CAR                       0
FLAG_OWN_REALTY                    0
NAME_TYPE_SUITE                  631
NAME_INCOME_TYPE                   0
NAME_EDUCATION_TYPE                0
NAME_FAMILY_STATUS                 0
NAME_HOUSING_TYPE                  0
OCCUPATION_TYPE                47367
WEEKDAY_APPR_PROCESS_START         0
ORGANIZATION_TYPE                  0
FONDKAPREMONT_MODE            102975
HOUSETYPE_MODE                 75586
WALLSMATERIAL_MODE             76535
EMERGENCYSTATE_MODE            71405
dtype: int64

In [24]:
'''train_c['NAME_TYPE_SUITE'].fillna(train_c['NAME_TYPE_SUITE'].mode()[0], inplace=True)

train_c['OCCUPATION_TYPE'].fillna(train_c['OCCUPATION_TYPE'].mode()[0], inplace=True)

train_c['FONDKAPREMONT_MODE'].fillna(train_c['FONDKAPREMONT_MODE'].mode()[0], inplace=True)

train_c['HOUSETYPE_MODE'].fillna(train_c['HOUSETYPE_MODE'].mode()[0], inplace=True)

train_c['WALLSMATERIAL_MODE'].fillna(train_c['WALLSMATERIAL_MODE'].mode()[0], inplace=True)

train_c['EMERGENCYSTATE_MODE'].fillna(train_c['EMERGENCYSTATE_MODE'].mode()[0], inplace=True)'''

train_c=train_c.fillna(train_c.mode().iloc[0])

In [25]:
train_c.isna().sum()

NAME_CONTRACT_TYPE            0
CODE_GENDER                   0
FLAG_OWN_CAR                  0
FLAG_OWN_REALTY               0
NAME_TYPE_SUITE               0
NAME_INCOME_TYPE              0
NAME_EDUCATION_TYPE           0
NAME_FAMILY_STATUS            0
NAME_HOUSING_TYPE             0
OCCUPATION_TYPE               0
WEEKDAY_APPR_PROCESS_START    0
ORGANIZATION_TYPE             0
FONDKAPREMONT_MODE            0
HOUSETYPE_MODE                0
WALLSMATERIAL_MODE            0
EMERGENCYSTATE_MODE           0
dtype: int64

In [26]:
train_n.isna().sum()[:50]

TARGET                               0
CNT_CHILDREN                         0
AMT_INCOME_TOTAL                     0
AMT_CREDIT                           0
AMT_ANNUITY                          5
AMT_GOODS_PRICE                    142
REGION_POPULATION_RELATIVE           0
DAYS_BIRTH                           0
DAYS_EMPLOYED                        0
DAYS_REGISTRATION                    0
DAYS_ID_PUBLISH                      0
OWN_CAR_AGE                      99515
FLAG_MOBIL                           0
FLAG_EMP_PHONE                       0
FLAG_WORK_PHONE                      0
FLAG_CONT_MOBILE                     0
FLAG_PHONE                           0
FLAG_EMAIL                           0
CNT_FAM_MEMBERS                      1
REGION_RATING_CLIENT                 0
REGION_RATING_CLIENT_W_CITY          0
HOUR_APPR_PROCESS_START              0
REG_REGION_NOT_LIVE_REGION           0
REG_REGION_NOT_WORK_REGION           0
LIVE_REGION_NOT_WORK_REGION          0
REG_CITY_NOT_LIVE_CITY               0
REG_CITY_NOT_WORK_CITY               0
LIVE_CITY_NOT_WORK_CITY              0
EXT_SOURCE_1                     85164
EXT_SOURCE_2                       323
EXT_SOURCE_3                     29842
APARTMENTS_AVG                   76367
BASEMENTAREA_AVG                 88107
YEARS_BEGINEXPLUATATION_AVG      73483
YEARS_BUILD_AVG                 100136
COMMONAREA_AVG                  105261
ELEVATORS_AVG                    80258
ENTRANCES_AVG                    75808
FLOORSMAX_AVG                    74878
FLOORSMIN_AVG                   102178
LANDAREA_AVG                     89304
LIVINGAPARTMENTS_AVG            102961
LIVINGAREA_AVG                   75587
NONLIVINGAPARTMENTS_AVG         104582
NONLIVINGAREA_AVG                83094
APARTMENTS_MODE                  76367
BASEMENTAREA_MODE                88107
YEARS_BEGINEXPLUATATION_MODE     73483
YEARS_BUILD_MODE                100136
COMMONAREA_MODE                 105261
dtype: int64

In [27]:
train_n.dtypes[:50]

TARGET                            int64
CNT_CHILDREN                      int64
AMT_INCOME_TOTAL                float64
AMT_CREDIT                      float64
AMT_ANNUITY                     float64
AMT_GOODS_PRICE                 float64
REGION_POPULATION_RELATIVE      float64
DAYS_BIRTH                        int64
DAYS_EMPLOYED                     int64
DAYS_REGISTRATION               float64
DAYS_ID_PUBLISH                   int64
OWN_CAR_AGE                     float64
FLAG_MOBIL                        int64
FLAG_EMP_PHONE                    int64
FLAG_WORK_PHONE                   int64
FLAG_CONT_MOBILE                  int64
FLAG_PHONE                        int64
FLAG_EMAIL                        int64
CNT_FAM_MEMBERS                 float64
REGION_RATING_CLIENT              int64
REGION_RATING_CLIENT_W_CITY       int64
HOUR_APPR_PROCESS_START           int64
REG_REGION_NOT_LIVE_REGION        int64
REG_REGION_NOT_WORK_REGION        int64
LIVE_REGION_NOT_WORK_REGION       int64
REG_CITY_NOT_LIVE_CITY            int64
REG_CITY_NOT_WORK_CITY            int64
LIVE_CITY_NOT_WORK_CITY           int64
EXT_SOURCE_1                    float64
EXT_SOURCE_2                    float64
EXT_SOURCE_3                    float64
APARTMENTS_AVG                  float64
BASEMENTAREA_AVG                float64
YEARS_BEGINEXPLUATATION_AVG     float64
YEARS_BUILD_AVG                 float64
COMMONAREA_AVG                  float64
ELEVATORS_AVG                   float64
ENTRANCES_AVG                   float64
FLOORSMAX_AVG                   float64
FLOORSMIN_AVG                   float64
LANDAREA_AVG                    float64
LIVINGAPARTMENTS_AVG            float64
LIVINGAREA_AVG                  float64
NONLIVINGAPARTMENTS_AVG         float64
NONLIVINGAREA_AVG               float64
APARTMENTS_MODE                 float64
BASEMENTAREA_MODE               float64
YEARS_BEGINEXPLUATATION_MODE    float64
YEARS_BUILD_MODE                float64
COMMONAREA_MODE                 float64
dtype: object

In [28]:
train_n.columns[50:]

Index(['ELEVATORS_MODE', 'ENTRANCES_MODE', 'FLOORSMAX_MODE', 'FLOORSMIN_MODE',
       'LANDAREA_MODE', 'LIVINGAPARTMENTS_MODE', 'LIVINGAREA_MODE',
       'NONLIVINGAPARTMENTS_MODE', 'NONLIVINGAREA_MODE', 'APARTMENTS_MEDI',
       'BASEMENTAREA_MEDI', 'YEARS_BEGINEXPLUATATION_MEDI', 'YEARS_BUILD_MEDI',
       'COMMONAREA_MEDI', 'ELEVATORS_MEDI', 'ENTRANCES_MEDI', 'FLOORSMAX_MEDI',
       'FLOORSMIN_MEDI', 'LANDAREA_MEDI', 'LIVINGAPARTMENTS_MEDI',
       'LIVINGAREA_MEDI', 'NONLIVINGAPARTMENTS_MEDI', 'NONLIVINGAREA_MEDI',
       'TOTALAREA_MODE', 'OBS_30_CNT_SOCIAL_CIRCLE',
       'DEF_30_CNT_SOCIAL_CIRCLE', 'OBS_60_CNT_SOCIAL_CIRCLE',
       'DEF_60_CNT_SOCIAL_CIRCLE', 'DAYS_LAST_PHONE_CHANGE', 'FLAG_DOCUMENT_2',
       'FLAG_DOCUMENT_3', 'FLAG_DOCUMENT_4', 'FLAG_DOCUMENT_5',
       'FLAG_DOCUMENT_6', 'FLAG_DOCUMENT_7', 'FLAG_DOCUMENT_8',
       'FLAG_DOCUMENT_9', 'FLAG_DOCUMENT_10', 'FLAG_DOCUMENT_11',
       'FLAG_DOCUMENT_12', 'FLAG_DOCUMENT_13', 'FLAG_DOCUMENT_14',
       'FLAG_DOCUMENT_15', 'FLAG_DOCUMENT_16', 'FLAG_DOCUMENT_17',
       'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20',
       'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR',
       'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
       'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT',
       'AMT_REQ_CREDIT_BUREAU_YEAR'],
      dtype='object')

In [29]:
train_n.isna().sum()[50:]

ELEVATORS_MODE                   80258
ENTRANCES_MODE                   75808
FLOORSMAX_MODE                   74878
FLOORSMIN_MODE                  102178
LANDAREA_MODE                    89304
LIVINGAPARTMENTS_MODE           102961
LIVINGAREA_MODE                  75587
NONLIVINGAPARTMENTS_MODE        104582
NONLIVINGAREA_MODE               83094
APARTMENTS_MEDI                  76367
BASEMENTAREA_MEDI                88107
YEARS_BEGINEXPLUATATION_MEDI     73483
YEARS_BUILD_MEDI                100136
COMMONAREA_MEDI                 105261
ELEVATORS_MEDI                   80258
ENTRANCES_MEDI                   75808
FLOORSMAX_MEDI                   74878
FLOORSMIN_MEDI                  102178
LANDAREA_MEDI                    89304
LIVINGAPARTMENTS_MEDI           102961
LIVINGAREA_MEDI                  75587
NONLIVINGAPARTMENTS_MEDI        104582
NONLIVINGAREA_MEDI               83094
TOTALAREA_MODE                   72698
OBS_30_CNT_SOCIAL_CIRCLE           508
DEF_30_CNT_SOCIAL_CIRCLE           508
OBS_60_CNT_SOCIAL_CIRCLE           508
DEF_60_CNT_SOCIAL_CIRCLE           508
DAYS_LAST_PHONE_CHANGE               0
FLAG_DOCUMENT_2                      0
FLAG_DOCUMENT_3                      0
FLAG_DOCUMENT_4                      0
FLAG_DOCUMENT_5                      0
FLAG_DOCUMENT_6                      0
FLAG_DOCUMENT_7                      0
FLAG_DOCUMENT_8                      0
FLAG_DOCUMENT_9                      0
FLAG_DOCUMENT_10                     0
FLAG_DOCUMENT_11                     0
FLAG_DOCUMENT_12                     0
FLAG_DOCUMENT_13                     0
FLAG_DOCUMENT_14                     0
FLAG_DOCUMENT_15                     0
FLAG_DOCUMENT_16                     0
FLAG_DOCUMENT_17                     0
FLAG_DOCUMENT_18                     0
FLAG_DOCUMENT_19                     0
FLAG_DOCUMENT_20                     0
FLAG_DOCUMENT_21                     0
AMT_REQ_CREDIT_BUREAU_HOUR       20424
AMT_REQ_CREDIT_BUREAU_DAY        20424
AMT_REQ_CREDIT_BUREAU_WEEK       20424
AMT_REQ_CREDIT_BUREAU_MON        20424
AMT_REQ_CREDIT_BUREAU_QRT        20424
AMT_REQ_CREDIT_BUREAU_YEAR       20424
dtype: int64

In [30]:
train_n.dtypes[50:]

ELEVATORS_MODE                  float64
ENTRANCES_MODE                  float64
FLOORSMAX_MODE                  float64
FLOORSMIN_MODE                  float64
LANDAREA_MODE                   float64
LIVINGAPARTMENTS_MODE           float64
LIVINGAREA_MODE                 float64
NONLIVINGAPARTMENTS_MODE        float64
NONLIVINGAREA_MODE              float64
APARTMENTS_MEDI                 float64
BASEMENTAREA_MEDI               float64
YEARS_BEGINEXPLUATATION_MEDI    float64
YEARS_BUILD_MEDI                float64
COMMONAREA_MEDI                 float64
ELEVATORS_MEDI                  float64
ENTRANCES_MEDI                  float64
FLOORSMAX_MEDI                  float64
FLOORSMIN_MEDI                  float64
LANDAREA_MEDI                   float64
LIVINGAPARTMENTS_MEDI           float64
LIVINGAREA_MEDI                 float64
NONLIVINGAPARTMENTS_MEDI        float64
NONLIVINGAREA_MEDI              float64
TOTALAREA_MODE                  float64
OBS_30_CNT_SOCIAL_CIRCLE        float64
DEF_30_CNT_SOCIAL_CIRCLE        float64
OBS_60_CNT_SOCIAL_CIRCLE        float64
DEF_60_CNT_SOCIAL_CIRCLE        float64
DAYS_LAST_PHONE_CHANGE          float64
FLAG_DOCUMENT_2                   int64
FLAG_DOCUMENT_3                   int64
FLAG_DOCUMENT_4                   int64
FLAG_DOCUMENT_5                   int64
FLAG_DOCUMENT_6                   int64
FLAG_DOCUMENT_7                   int64
FLAG_DOCUMENT_8                   int64
FLAG_DOCUMENT_9                   int64
FLAG_DOCUMENT_10                  int64
FLAG_DOCUMENT_11                  int64
FLAG_DOCUMENT_12                  int64
FLAG_DOCUMENT_13                  int64
FLAG_DOCUMENT_14                  int64
FLAG_DOCUMENT_15                  int64
FLAG_DOCUMENT_16                  int64
FLAG_DOCUMENT_17                  int64
FLAG_DOCUMENT_18                  int64
FLAG_DOCUMENT_19                  int64
FLAG_DOCUMENT_20                  int64
FLAG_DOCUMENT_21                  int64
AMT_REQ_CREDIT_BUREAU_HOUR      float64
AMT_REQ_CREDIT_BUREAU_DAY       float64
AMT_REQ_CREDIT_BUREAU_WEEK      float64
AMT_REQ_CREDIT_BUREAU_MON       float64
AMT_REQ_CREDIT_BUREAU_QRT       float64
AMT_REQ_CREDIT_BUREAU_YEAR      float64
dtype: object

In [31]:
cols = ['AMT_ANNUITY', 'AMT_GOODS_PRICE', 'OWN_CAR_AGE', 'CNT_FAM_MEMBERS',
       'EXT_SOURCE_1','EXT_SOURCE_2','EXT_SOURCE_3', 'APARTMENTS_AVG', 'BASEMENTAREA_AVG',
       'YEARS_BEGINEXPLUATATION_AVG', 'YEARS_BUILD_AVG', 'COMMONAREA_AVG',
       'ELEVATORS_AVG', 'ENTRANCES_AVG', 'FLOORSMAX_AVG', 'FLOORSMIN_AVG',
       'LANDAREA_AVG', 'LIVINGAPARTMENTS_AVG', 'LIVINGAREA_AVG',
       'NONLIVINGAPARTMENTS_AVG', 'NONLIVINGAREA_AVG', 'APARTMENTS_MODE',
       'BASEMENTAREA_MODE', 'YEARS_BEGINEXPLUATATION_MODE', 'YEARS_BUILD_MODE',
       'COMMONAREA_MODE', 'ELEVATORS_MODE', 'ENTRANCES_MODE', 'FLOORSMAX_MODE', 'FLOORSMIN_MODE', 'LANDAREA_MODE',
       'LIVINGAPARTMENTS_MODE', 'LIVINGAREA_MODE', 'NONLIVINGAPARTMENTS_MODE',
       'NONLIVINGAREA_MODE', 'APARTMENTS_MEDI', 'BASEMENTAREA_MEDI',
       'YEARS_BEGINEXPLUATATION_MEDI', 'YEARS_BUILD_MEDI', 'COMMONAREA_MEDI',
       'ELEVATORS_MEDI', 'ENTRANCES_MEDI', 'FLOORSMAX_MEDI', 'FLOORSMIN_MEDI',
       'LANDAREA_MEDI', 'LIVINGAPARTMENTS_MEDI', 'LIVINGAREA_MEDI',
       'NONLIVINGAPARTMENTS_MEDI', 'NONLIVINGAREA_MEDI', 'TOTALAREA_MODE',
       'OBS_30_CNT_SOCIAL_CIRCLE', 'DEF_30_CNT_SOCIAL_CIRCLE',
       'OBS_60_CNT_SOCIAL_CIRCLE', 'DEF_60_CNT_SOCIAL_CIRCLE','AMT_REQ_CREDIT_BUREAU_HOUR', 'AMT_REQ_CREDIT_BUREAU_DAY',
       'AMT_REQ_CREDIT_BUREAU_WEEK', 'AMT_REQ_CREDIT_BUREAU_MON',
       'AMT_REQ_CREDIT_BUREAU_QRT', 'AMT_REQ_CREDIT_BUREAU_YEAR']

#train_n[cols]=train_n[cols].fillna(train_n.mean().iloc[0])
train_n=train_n.fillna(train_n.mean().iloc[0])

#verifiqué que todos fueran float para no tener que redondear

In [32]:
train_n.isna().sum()[:50]

TARGET                          0
CNT_CHILDREN                    0
AMT_INCOME_TOTAL                0
AMT_CREDIT                      0
AMT_ANNUITY                     0
AMT_GOODS_PRICE                 0
REGION_POPULATION_RELATIVE      0
DAYS_BIRTH                      0
DAYS_EMPLOYED                   0
DAYS_REGISTRATION               0
DAYS_ID_PUBLISH                 0
OWN_CAR_AGE                     0
FLAG_MOBIL                      0
FLAG_EMP_PHONE                  0
FLAG_WORK_PHONE                 0
FLAG_CONT_MOBILE                0
FLAG_PHONE                      0
FLAG_EMAIL                      0
CNT_FAM_MEMBERS                 0
REGION_RATING_CLIENT            0
REGION_RATING_CLIENT_W_CITY     0
HOUR_APPR_PROCESS_START         0
REG_REGION_NOT_LIVE_REGION      0
REG_REGION_NOT_WORK_REGION      0
LIVE_REGION_NOT_WORK_REGION     0
REG_CITY_NOT_LIVE_CITY          0
REG_CITY_NOT_WORK_CITY          0
LIVE_CITY_NOT_WORK_CITY         0
EXT_SOURCE_1                    0
EXT_SOURCE_2                    0
EXT_SOURCE_3                    0
APARTMENTS_AVG                  0
BASEMENTAREA_AVG                0
YEARS_BEGINEXPLUATATION_AVG     0
YEARS_BUILD_AVG                 0
COMMONAREA_AVG                  0
ELEVATORS_AVG                   0
ENTRANCES_AVG                   0
FLOORSMAX_AVG                   0
FLOORSMIN_AVG                   0
LANDAREA_AVG                    0
LIVINGAPARTMENTS_AVG            0
LIVINGAREA_AVG                  0
NONLIVINGAPARTMENTS_AVG         0
NONLIVINGAREA_AVG               0
APARTMENTS_MODE                 0
BASEMENTAREA_MODE               0
YEARS_BEGINEXPLUATATION_MODE    0
YEARS_BUILD_MODE                0
COMMONAREA_MODE                 0
dtype: int64

In [33]:
train_n.isna().sum()[50:]

ELEVATORS_MODE                  0
ENTRANCES_MODE                  0
FLOORSMAX_MODE                  0
FLOORSMIN_MODE                  0
LANDAREA_MODE                   0
LIVINGAPARTMENTS_MODE           0
LIVINGAREA_MODE                 0
NONLIVINGAPARTMENTS_MODE        0
NONLIVINGAREA_MODE              0
APARTMENTS_MEDI                 0
BASEMENTAREA_MEDI               0
YEARS_BEGINEXPLUATATION_MEDI    0
YEARS_BUILD_MEDI                0
COMMONAREA_MEDI                 0
ELEVATORS_MEDI                  0
ENTRANCES_MEDI                  0
FLOORSMAX_MEDI                  0
FLOORSMIN_MEDI                  0
LANDAREA_MEDI                   0
LIVINGAPARTMENTS_MEDI           0
LIVINGAREA_MEDI                 0
NONLIVINGAPARTMENTS_MEDI        0
NONLIVINGAREA_MEDI              0
TOTALAREA_MODE                  0
OBS_30_CNT_SOCIAL_CIRCLE        0
DEF_30_CNT_SOCIAL_CIRCLE        0
OBS_60_CNT_SOCIAL_CIRCLE        0
DEF_60_CNT_SOCIAL_CIRCLE        0
DAYS_LAST_PHONE_CHANGE          0
FLAG_DOCUMENT_2                 0
FLAG_DOCUMENT_3                 0
FLAG_DOCUMENT_4                 0
FLAG_DOCUMENT_5                 0
FLAG_DOCUMENT_6                 0
FLAG_DOCUMENT_7                 0
FLAG_DOCUMENT_8                 0
FLAG_DOCUMENT_9                 0
FLAG_DOCUMENT_10                0
FLAG_DOCUMENT_11                0
FLAG_DOCUMENT_12                0
FLAG_DOCUMENT_13                0
FLAG_DOCUMENT_14                0
FLAG_DOCUMENT_15                0
FLAG_DOCUMENT_16                0
FLAG_DOCUMENT_17                0
FLAG_DOCUMENT_18                0
FLAG_DOCUMENT_19                0
FLAG_DOCUMENT_20                0
FLAG_DOCUMENT_21                0
AMT_REQ_CREDIT_BUREAU_HOUR      0
AMT_REQ_CREDIT_BUREAU_DAY       0
AMT_REQ_CREDIT_BUREAU_WEEK      0
AMT_REQ_CREDIT_BUREAU_MON       0
AMT_REQ_CREDIT_BUREAU_QRT       0
AMT_REQ_CREDIT_BUREAU_YEAR      0
dtype: int64

In [34]:
scaler = StandardScaler() #media cero y desv standart 1
target = train_n['TARGET'] 
train_n= train_n.drop(columns='TARGET') #target es lo que predecimos - target es y
train_n[:] = scaler.fit_transform(train_n) #aplico standar scaler
train_n.head()

,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,-0.576313,-0.301564,0.587869,0.263743,0.370435,-1.059226,-0.642414,2.129407,-1.854951,0.397258,...,-0.090795,-0.023897,-0.023335,-0.019453,-0.20009,-0.157209,-0.213627,-0.284527,-0.418835,-0.897033
1,-0.576313,-0.588114,0.149959,-0.058781,0.138740,-0.144653,-1.239540,2.129407,0.480197,-0.927181,...,-0.090795,-0.023897,-0.023335,-0.019453,-0.20009,-0.157209,-0.213627,-0.284527,-0.418835,1.273067
2,-0.576313,-0.301564,-0.946995,-0.276594,-0.934374,-1.075535,0.756536,-0.467982,1.083465,1.274260,...,-0.090795,-0.023897,-0.023335,-0.019453,-0.20009,-0.157209,-0.213627,-0.284527,-0.418835,-0.354508
3,-0.576313,-0.915599,0.188475,0.456698,0.370435,-0.083836,-0.915648,-0.481831,-1.699387,-0.387080,...,-0.090795,-0.023897,-0.023335,-0.019453,-0.20009,-0.157209,-0.213627,-0.284527,1.326947,3.985693
4,-0.576313,1.335864,0.748792,1.233491,0.980159,-0.775510,-1.321831,2.129407,0.667780,-1.060882,...,-0.090795,-0.023897,-0.023335,-0.019453,-0.20009,-0.157209,-0.213627,0.911625,-0.418835,-0.354508

In [35]:
#hacer con cada categorical
train_c=pd.get_dummies(data=train_c)
train = pd.concat([train_n,train_c], axis=1)
train

,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,...,HOUSETYPE_MODE_terraced house,WALLSMATERIAL_MODE_Block,WALLSMATERIAL_MODE_Mixed,WALLSMATERIAL_MODE_Monolithic,WALLSMATERIAL_MODE_Others,WALLSMATERIAL_MODE_Panel,"WALLSMATERIAL_MODE_Stone, brick",WALLSMATERIAL_MODE_Wooden,EMERGENCYSTATE_MODE_No,EMERGENCYSTATE_MODE_Yes
0,-0.576313,-0.301564,0.587869,0.263743,0.370435,-1.059226,-0.642414,2.129407,-1.854951,0.397258,...,0,0,0,0,0,1,0,0,1,0
1,-0.576313,-0.588114,0.149959,-0.058781,0.138740,-0.144653,-1.239540,2.129407,0.480197,-0.927181,...,0,0,0,0,0,1,0,0,1,0
2,-0.576313,-0.301564,-0.946995,-0.276594,-0.934374,-1.075535,0.756536,-0.467982,1.083465,1.274260,...,0,0,0,0,0,1,0,0,1,0
3,-0.576313,-0.915599,0.188475,0.456698,0.370435,-0.083836,-0.915648,-0.481831,-1.699387,-0.387080,...,0,1,0,0,0,0,0,0,1,0
4,-0.576313,1.335864,0.748792,1.233491,0.980159,-0.775510,-1.321831,2.129407,0.667780,-1.060882,...,0,0,0,0,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150674,-0.576313,-0.506242,-1.213391,-1.072030,-1.190458,-0.144653,-0.509464,-0.483980,-0.057615,0.775858,...,0,0,0,0,0,1,0,0,1,0
150675,-0.576313,-0.301564,0.454738,0.404808,0.370435,-0.929763,0.098894,-0.495022,0.792741,-1.688352,...,0,0,0,0,0,0,1,0,1,0
150676,-0.576313,-0.301564,-0.988189,-1.174566,-0.909985,-0.979707,-1.346358,2.129407,0.875198,1.506583,...,0,0,0,0,0,1,0,0,1,0
150677,0.812922,-0.301564,-0.226170,-0.386277,-0.227094,1.839326,0.912407,-0.476316,0.560671,-0.713391,...,0,0,0,0,0,1,0,0,1,0
150678,0.812922,-0.915599,-1.044221,-1.252245,-0.970957,-0.739556,1.008910,-0.478564,0.594107,0.053738,...,0,0,0,0,0,0,1,0,1,0

In [36]:
train.columns[:100]

Index(['CNT_CHILDREN', 'AMT_INCOME_TOTAL', 'AMT_CREDIT', 'AMT_ANNUITY',
       'AMT_GOODS_PRICE', 'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH',
       'DAYS_EMPLOYED', 'DAYS_REGISTRATION', 'DAYS_ID_PUBLISH', 'OWN_CAR_AGE',
       'FLAG_MOBIL', 'FLAG_EMP_PHONE', 'FLAG_WORK_PHONE', 'FLAG_CONT_MOBILE',
       'FLAG_PHONE', 'FLAG_EMAIL', 'CNT_FAM_MEMBERS', 'REGION_RATING_CLIENT',
       'REGION_RATING_CLIENT_W_CITY', 'HOUR_APPR_PROCESS_START',
       'REG_REGION_NOT_LIVE_REGION', 'REG_REGION_NOT_WORK_REGION',
       'LIVE_REGION_NOT_WORK_REGION', 'REG_CITY_NOT_LIVE_CITY',
       'REG_CITY_NOT_WORK_CITY', 'LIVE_CITY_NOT_WORK_CITY', 'EXT_SOURCE_1',
       'EXT_SOURCE_2', 'EXT_SOURCE_3', 'APARTMENTS_AVG', 'BASEMENTAREA_AVG',
       'YEARS_BEGINEXPLUATATION_AVG', 'YEARS_BUILD_AVG', 'COMMONAREA_AVG',
       'ELEVATORS_AVG', 'ENTRANCES_AVG', 'FLOORSMAX_AVG', 'FLOORSMIN_AVG',
       'LANDAREA_AVG', 'LIVINGAPARTMENTS_AVG', 'LIVINGAREA_AVG',
       'NONLIVINGAPARTMENTS_AVG', 'NONLIVINGAREA_AVG', 'APARTMENTS_MODE',
       'BASEMENTAREA_MODE', 'YEARS_BEGINEXPLUATATION_MODE', 'YEARS_BUILD_MODE',
       'COMMONAREA_MODE', 'ELEVATORS_MODE', 'ENTRANCES_MODE', 'FLOORSMAX_MODE',
       'FLOORSMIN_MODE', 'LANDAREA_MODE', 'LIVINGAPARTMENTS_MODE',
       'LIVINGAREA_MODE', 'NONLIVINGAPARTMENTS_MODE', 'NONLIVINGAREA_MODE',
       'APARTMENTS_MEDI', 'BASEMENTAREA_MEDI', 'YEARS_BEGINEXPLUATATION_MEDI',
       'YEARS_BUILD_MEDI', 'COMMONAREA_MEDI', 'ELEVATORS_MEDI',
       'ENTRANCES_MEDI', 'FLOORSMAX_MEDI', 'FLOORSMIN_MEDI', 'LANDAREA_MEDI',
       'LIVINGAPARTMENTS_MEDI', 'LIVINGAREA_MEDI', 'NONLIVINGAPARTMENTS_MEDI',
       'NONLIVINGAREA_MEDI', 'TOTALAREA_MODE', 'OBS_30_CNT_SOCIAL_CIRCLE',
       'DEF_30_CNT_SOCIAL_CIRCLE', 'OBS_60_CNT_SOCIAL_CIRCLE',
       'DEF_60_CNT_SOCIAL_CIRCLE', 'DAYS_LAST_PHONE_CHANGE', 'FLAG_DOCUMENT_2',
       'FLAG_DOCUMENT_3', 'FLAG_DOCUMENT_4', 'FLAG_DOCUMENT_5',
       'FLAG_DOCUMENT_6', 'FLAG_DOCUMENT_7', 'FLAG_DOCUMENT_8',
       'FLAG_DOCUMENT_9', 'FLAG_DOCUMENT_10', 'FLAG_DOCUMENT_11',
       'FLAG_DOCUMENT_12', 'FLAG_DOCUMENT_13', 'FLAG_DOCUMENT_14',
       'FLAG_DOCUMENT_15', 'FLAG_DOCUMENT_16', 'FLAG_DOCUMENT_17',
       'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20',
       'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR',
       'AMT_REQ_CREDIT_BUREAU_DAY'],
      dtype='object')

In [37]:
train.columns[100:200]

Index(['AMT_REQ_CREDIT_BUREAU_WEEK', 'AMT_REQ_CREDIT_BUREAU_MON',
       'AMT_REQ_CREDIT_BUREAU_QRT', 'AMT_REQ_CREDIT_BUREAU_YEAR',
       'NAME_CONTRACT_TYPE_Cash loans', 'NAME_CONTRACT_TYPE_Revolving loans',
       'CODE_GENDER_F', 'CODE_GENDER_M', 'CODE_GENDER_XNA', 'FLAG_OWN_CAR_N',
       'FLAG_OWN_CAR_Y', 'FLAG_OWN_REALTY_N', 'FLAG_OWN_REALTY_Y',
       'NAME_TYPE_SUITE_Children', 'NAME_TYPE_SUITE_Family',
       'NAME_TYPE_SUITE_Group of people', 'NAME_TYPE_SUITE_Other_A',
       'NAME_TYPE_SUITE_Other_B', 'NAME_TYPE_SUITE_Spouse, partner',
       'NAME_TYPE_SUITE_Unaccompanied', 'NAME_INCOME_TYPE_Businessman',
       'NAME_INCOME_TYPE_Commercial associate',
       'NAME_INCOME_TYPE_Maternity leave', 'NAME_INCOME_TYPE_Pensioner',
       'NAME_INCOME_TYPE_State servant', 'NAME_INCOME_TYPE_Student',
       'NAME_INCOME_TYPE_Unemployed', 'NAME_INCOME_TYPE_Working',
       'NAME_EDUCATION_TYPE_Academic degree',
       'NAME_EDUCATION_TYPE_Higher education',
       'NAME_EDUCATION_TYPE_Incomplete higher',
       'NAME_EDUCATION_TYPE_Lower secondary',
       'NAME_EDUCATION_TYPE_Secondary / secondary special',
       'NAME_FAMILY_STATUS_Civil marriage', 'NAME_FAMILY_STATUS_Married',
       'NAME_FAMILY_STATUS_Separated',
       'NAME_FAMILY_STATUS_Single / not married', 'NAME_FAMILY_STATUS_Unknown',
       'NAME_FAMILY_STATUS_Widow', 'NAME_HOUSING_TYPE_Co-op apartment',
       'NAME_HOUSING_TYPE_House / apartment',
       'NAME_HOUSING_TYPE_Municipal apartment',
       'NAME_HOUSING_TYPE_Office apartment',
       'NAME_HOUSING_TYPE_Rented apartment', 'NAME_HOUSING_TYPE_With parents',
       'OCCUPATION_TYPE_Accountants', 'OCCUPATION_TYPE_Cleaning staff',
       'OCCUPATION_TYPE_Cooking staff', 'OCCUPATION_TYPE_Core staff',
       'OCCUPATION_TYPE_Drivers', 'OCCUPATION_TYPE_HR staff',
       'OCCUPATION_TYPE_High skill tech staff', 'OCCUPATION_TYPE_IT staff',
       'OCCUPATION_TYPE_Laborers', 'OCCUPATION_TYPE_Low-skill Laborers',
       'OCCUPATION_TYPE_Managers', 'OCCUPATION_TYPE_Medicine staff',
       'OCCUPATION_TYPE_Private service staff',
       'OCCUPATION_TYPE_Realty agents', 'OCCUPATION_TYPE_Sales staff',
       'OCCUPATION_TYPE_Secretaries', 'OCCUPATION_TYPE_Security staff',
       'OCCUPATION_TYPE_Waiters/barmen staff',
       'WEEKDAY_APPR_PROCESS_START_FRIDAY',
       'WEEKDAY_APPR_PROCESS_START_MONDAY',
       'WEEKDAY_APPR_PROCESS_START_SATURDAY',
       'WEEKDAY_APPR_PROCESS_START_SUNDAY',
       'WEEKDAY_APPR_PROCESS_START_THURSDAY',
       'WEEKDAY_APPR_PROCESS_START_TUESDAY',
       'WEEKDAY_APPR_PROCESS_START_WEDNESDAY', 'ORGANIZATION_TYPE_Advertising',
       'ORGANIZATION_TYPE_Agriculture', 'ORGANIZATION_TYPE_Bank',
       'ORGANIZATION_TYPE_Business Entity Type 1',
       'ORGANIZATION_TYPE_Business Entity Type 2',
       'ORGANIZATION_TYPE_Business Entity Type 3',
       'ORGANIZATION_TYPE_Cleaning', 'ORGANIZATION_TYPE_Construction',
       'ORGANIZATION_TYPE_Culture', 'ORGANIZATION_TYPE_Electricity',
       'ORGANIZATION_TYPE_Emergency', 'ORGANIZATION_TYPE_Government',
       'ORGANIZATION_TYPE_Hotel', 'ORGANIZATION_TYPE_Housing',
       'ORGANIZATION_TYPE_Industry: type 1',
       'ORGANIZATION_TYPE_Industry: type 10',
       'ORGANIZATION_TYPE_Industry: type 11',
       'ORGANIZATION_TYPE_Industry: type 12',
       'ORGANIZATION_TYPE_Industry: type 13',
       'ORGANIZATION_TYPE_Industry: type 2',
       'ORGANIZATION_TYPE_Industry: type 3',
       'ORGANIZATION_TYPE_Industry: type 4',
       'ORGANIZATION_TYPE_Industry: type 5',
       'ORGANIZATION_TYPE_Industry: type 6',
       'ORGANIZATION_TYPE_Industry: type 7',
       'ORGANIZATION_TYPE_Industry: type 8',
       'ORGANIZATION_TYPE_Industry: type 9', 'ORGANIZATION_TYPE_Insurance',
       'ORGANIZATION_TYPE_Kindergarten', 'ORGANIZATION_TYPE_Legal Services'],
      dtype='object')

In [38]:
#l=test.columns.tolist()
#l_1=train.columns.tolist()
#[item for item in l_1 if item not in l]

In [39]:
train=train.reindex(sorted(train.columns), axis=1) #reordenarlas para tenerlas en orden alfabético

In [40]:
X = train#.drop(columns='TARGET')
y = target#train['TARGET']

In [41]:
# split dataset


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [42]:
from sklearn.model_selection import GridSearchCV
parameters = [{'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']},
              {'penalty':['none', 'elasticnet', 'l1', 'l2']},
              {'C':[0.001, 0.01, 0.1, 1, 10, 100]}] #,
              #{'class_weight':['None','balanced']},
              #{'dual':[True,False]},
              #{'max_iter':[100,200,300,400,500]},
              #{'tol':[1e-4,1e-5,1e-6]}


lr = LogisticRegression(random_state=0) #clasificador
grid_searchlr = GridSearchCV(estimator = lr,  
                           param_grid = parameters,
                           scoring = 'f1',
                           verbose=0)

grid_searchlr.fit(X_train, y_train)

C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning:
10 fits failed out of a total of 75.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py", line 1091, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py", line 61, in _check_solver
    raise ValueError(
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py", line 1091, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py", line 61, in _check_solver
    raise ValueError(
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\model_selection\_search.py:953: UserWarning: One or more of the test scores are non-finite: [0.00589307 0.00611129 0.00589307 0.00503391 0.00459914 0.00676239
        nan        nan 0.00611129 0.00175848 0.00416283 0.00568068
 0.00611129 0.00589354 0.00654571]
  warnings.warn(

C:\Users\Javiera\anaconda3\envs\mat_281\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

GridSearchCV(estimator=LogisticRegression(random_state=0),
             param_grid=[{'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                     'saga']},
                         {'penalty': ['none', 'elasticnet', 'l1', 'l2']},
                         {'C': [0.001, 0.01, 0.1, 1, 10, 100]}],
             scoring='f1')

In [43]:
grid_searchlr.best_estimator_

LogisticRegression(penalty='none', random_state=0)

In [44]:
grid_searchlr.best_score_

0.006762393149699587

In [45]:

parametersper = [{'penalty':['none', 'elasticnet', 'l1', 'l2']},
              {'alpha':[0.0001,0.001, 0.01, 0.1, 1, 10]},
              {'max_iter':[1000,1200,1300,1400,1500]},
              {'tol':[1e-4,1e-3]}]


per = Perceptron(random_state=0)
grid_searchper = GridSearchCV(estimator = per,
                           param_grid = parametersper,
                           scoring = 'roc_auc',
                           verbose=0)

grid_searchper.fit(X_train, y_train)

GridSearchCV(estimator=Perceptron(),
             param_grid=[{'penalty': ['none', 'elasticnet', 'l1', 'l2']},
                         {'alpha': [0.0001, 0.001, 0.01, 0.1, 1, 10]},
                         {'max_iter': [1000, 1200, 1300, 1400, 1500]},
                         {'tol': [0.0001, 0.001]}],
             scoring='roc_auc')

In [46]:
grid_searchper.best_estimator_

Perceptron(penalty='none')

In [47]:
grid_searchper.best_score_

0.6220186072718237

In [48]:
X_test

,AMT_ANNUITY,AMT_CREDIT,AMT_GOODS_PRICE,AMT_INCOME_TOTAL,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_YEAR,...,WEEKDAY_APPR_PROCESS_START_SUNDAY,WEEKDAY_APPR_PROCESS_START_THURSDAY,WEEKDAY_APPR_PROCESS_START_TUESDAY,WEEKDAY_APPR_PROCESS_START_WEDNESDAY,YEARS_BEGINEXPLUATATION_AVG,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_AVG,YEARS_BUILD_MEDI,YEARS_BUILD_MODE
76389,-0.605643,-0.821215,-0.849012,-0.015014,-0.157209,-0.20009,-0.284527,-0.418835,-0.213627,1.815592,...,0,1,0,0,-1.020473,-1.020395,-1.019760,-0.695760,-0.696189,-0.696842
57086,0.158410,-0.371841,-0.239289,-0.096886,-0.157209,-0.20009,-0.284527,-0.418835,-0.213627,-0.354508,...,0,0,1,0,0.976453,0.976292,0.977087,1.303132,1.305403,1.316845
127028,-0.941528,-0.820094,-0.727068,-0.301564,-0.157209,-0.20009,-0.284527,-0.418835,-0.213627,-0.354508,...,0,0,0,1,0.954471,0.954313,0.952886,0.883140,0.893012,0.876753
21705,-0.562764,-1.010422,-0.995346,-0.547178,-0.157209,-0.20009,-0.284527,-0.418835,-0.213627,-0.897033,...,0,0,0,0,-1.020473,-1.020395,-1.019760,-0.695760,-0.696189,-0.696842
144438,1.249648,1.634540,1.589882,0.455746,-0.157209,-0.20009,-0.284527,-0.418835,-0.213627,0.188017,...,0,0,0,0,-1.020473,-1.020395,-1.019760,-0.695760,-0.696189,-0.696842
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145958,-1.044997,-0.821215,-0.849012,-1.038406,-0.157209,-0.20009,-0.284527,-0.418835,-0.213627,-0.354508,...,0,1,0,0,-1.020473,-1.020395,-1.019760,-0.695760,-0.696189,-0.696842
96138,1.099572,0.539301,0.589936,1.335864,-0.157209,-0.20009,0.911625,-0.418835,-0.213627,-0.897033,...,0,0,0,0,1.011756,1.011592,1.012389,-0.695760,-0.696189,-0.696842
40168,-0.853906,-0.946995,-0.934374,0.312471,-0.157209,-0.20009,0.911625,-0.418835,-0.213627,-0.354508,...,0,0,0,0,0.987554,0.987393,0.988189,-0.695760,-0.696189,-0.696842
19833,0.668296,-0.226170,-0.227094,-0.547178,-0.157209,-0.20009,-0.284527,-0.418835,-0.213627,-0.897033,...,1,0,0,0,0.999766,0.999603,1.000400,1.744124,1.738705,1.736738
28044,1.047993,0.691057,0.492380,0.517150,-0.157209,-0.20009,-0.284527,-0.418835,5.071248,-0.354508,...,0,0,0,0,0.965573,0.965414,0.966208,1.093136,1.099054,1.116692

In [49]:
clf = LogisticRegression(solver="liblinear", random_state=0).fit(X_train, y_train)
#clf = Perceptron(tol=1e-3,eta0=0.1,random_state=0).fit(X_train,y_train)
score=roc_auc_score(y_test, clf.predict(X_test))
score

0.501585102236405

In [50]:
#MEJOR
clf = Perceptron(tol=1e-5,eta0=0.1,penalty=  'l2',random_state=42).fit(X_train,y_train)
score=roc_auc_score(y_test, clf.predict(X_test))
score

0.5875573986261016

In [51]:
clf = LogisticRegression(solver="newton-cg", random_state=0).fit(X_train, y_train)
#clf = Perceptron(tol=1e-3,eta0=0.1,random_state=0).fit(X_train,y_train)
score=roc_auc_score(y_test, clf.predict(X_test)) #roc_auc_score es la métrica
score

0.501585102236405

In [52]:
#clf = LogisticRegression(solver="liblinear", random_state=0).fit(X_train, y_train)
clf = Perceptron(tol=1e-5,eta0=0.1,random_state=0).fit(X_train,y_train)
score=roc_auc_score(y_test, clf.predict(X_test))
score

0.5151905447008694

In [53]:
#clf = LogisticRegression(solver="liblinear", random_state=0).fit(X_train, y_train)
clf = Perceptron(tol=1e-5,eta0=0.1,random_state=42).fit(X_train,y_train)
score=roc_auc_score(y_test, clf.predict(X_test))
score

0.5185228082563625

In [54]:
#df_stest1=df_stest.merge(df_hpydf_hpmydf_tcm, how='outer', on='SK_ID_CURR')

In [55]:
#acá lo hago todo de nuevo pero para el data de test

df_test = df_stest.iloc[:,1:]
df_test=df_test.drop(columns='SK_ID_CURR') #,'TARGET'])
numerical = [var for var in df_test.columns if df_test[var].dtype!='O']

test_c=df_test[categorical]
test_n=df_test[numerical]

In [56]:
test_c.isna().sum()[:50]

NAME_CONTRACT_TYPE                0
CODE_GENDER                       0
FLAG_OWN_CAR                      0
FLAG_OWN_REALTY                   0
NAME_TYPE_SUITE                 263
NAME_INCOME_TYPE                  0
NAME_EDUCATION_TYPE               0
NAME_FAMILY_STATUS                0
NAME_HOUSING_TYPE                 0
OCCUPATION_TYPE               20179
WEEKDAY_APPR_PROCESS_START        0
ORGANIZATION_TYPE                 0
FONDKAPREMONT_MODE            44130
HOUSETYPE_MODE                32398
WALLSMATERIAL_MODE            32839
EMERGENCYSTATE_MODE           30569
dtype: int64

In [57]:
test_c=test_c.fillna(test_c.mode().iloc[0])
test_c.isna().sum()[:]

NAME_CONTRACT_TYPE            0
CODE_GENDER                   0
FLAG_OWN_CAR                  0
FLAG_OWN_REALTY               0
NAME_TYPE_SUITE               0
NAME_INCOME_TYPE              0
NAME_EDUCATION_TYPE           0
NAME_FAMILY_STATUS            0
NAME_HOUSING_TYPE             0
OCCUPATION_TYPE               0
WEEKDAY_APPR_PROCESS_START    0
ORGANIZATION_TYPE             0
FONDKAPREMONT_MODE            0
HOUSETYPE_MODE                0
WALLSMATERIAL_MODE            0
EMERGENCYSTATE_MODE           0
dtype: int64

In [58]:
test_n.isna().sum()[:50]

CNT_CHILDREN                        0
AMT_INCOME_TOTAL                    0
AMT_CREDIT                          0
AMT_ANNUITY                         2
AMT_GOODS_PRICE                    47
REGION_POPULATION_RELATIVE          0
DAYS_BIRTH                          0
DAYS_EMPLOYED                       0
DAYS_REGISTRATION                   0
DAYS_ID_PUBLISH                     0
OWN_CAR_AGE                     42542
FLAG_MOBIL                          0
FLAG_EMP_PHONE                      0
FLAG_WORK_PHONE                     0
FLAG_CONT_MOBILE                    0
FLAG_PHONE                          0
FLAG_EMAIL                          0
CNT_FAM_MEMBERS                     0
REGION_RATING_CLIENT                0
REGION_RATING_CLIENT_W_CITY         0
HOUR_APPR_PROCESS_START             0
REG_REGION_NOT_LIVE_REGION          0
REG_REGION_NOT_WORK_REGION          0
LIVE_REGION_NOT_WORK_REGION         0
REG_CITY_NOT_LIVE_CITY              0
REG_CITY_NOT_WORK_CITY              0
LIVE_CITY_NOT_WORK_CITY             0
EXT_SOURCE_1                    36241
EXT_SOURCE_2                      133
EXT_SOURCE_3                    12881
APARTMENTS_AVG                  32767
BASEMENTAREA_AVG                37711
YEARS_BEGINEXPLUATATION_AVG     31478
YEARS_BUILD_AVG                 42925
COMMONAREA_AVG                  45076
ELEVATORS_AVG                   34397
ENTRANCES_AVG                   32525
FLOORSMAX_AVG                   32153
FLOORSMIN_AVG                   43811
LANDAREA_AVG                    38386
LIVINGAPARTMENTS_AVG            44162
LIVINGAREA_AVG                  32369
NONLIVINGAPARTMENTS_AVG         44877
NONLIVINGAREA_AVG               35580
APARTMENTS_MODE                 32767
BASEMENTAREA_MODE               37711
YEARS_BEGINEXPLUATATION_MODE    31478
YEARS_BUILD_MODE                42925
COMMONAREA_MODE                 45076
ELEVATORS_MODE                  34397
dtype: int64

In [59]:
test_n.isna().sum()[50:]

ENTRANCES_MODE                  32525
FLOORSMAX_MODE                  32153
FLOORSMIN_MODE                  43811
LANDAREA_MODE                   38386
LIVINGAPARTMENTS_MODE           44162
LIVINGAREA_MODE                 32369
NONLIVINGAPARTMENTS_MODE        44877
NONLIVINGAREA_MODE              35580
APARTMENTS_MEDI                 32767
BASEMENTAREA_MEDI               37711
YEARS_BEGINEXPLUATATION_MEDI    31478
YEARS_BUILD_MEDI                42925
COMMONAREA_MEDI                 45076
ELEVATORS_MEDI                  34397
ENTRANCES_MEDI                  32525
FLOORSMAX_MEDI                  32153
FLOORSMIN_MEDI                  43811
LANDAREA_MEDI                   38386
LIVINGAPARTMENTS_MEDI           44162
LIVINGAREA_MEDI                 32369
NONLIVINGAPARTMENTS_MEDI        44877
NONLIVINGAREA_MEDI              35580
TOTALAREA_MODE                  31137
OBS_30_CNT_SOCIAL_CIRCLE          221
DEF_30_CNT_SOCIAL_CIRCLE          221
OBS_60_CNT_SOCIAL_CIRCLE          221
DEF_60_CNT_SOCIAL_CIRCLE          221
DAYS_LAST_PHONE_CHANGE              0
FLAG_DOCUMENT_2                     0
FLAG_DOCUMENT_3                     0
FLAG_DOCUMENT_4                     0
FLAG_DOCUMENT_5                     0
FLAG_DOCUMENT_6                     0
FLAG_DOCUMENT_7                     0
FLAG_DOCUMENT_8                     0
FLAG_DOCUMENT_9                     0
FLAG_DOCUMENT_10                    0
FLAG_DOCUMENT_11                    0
FLAG_DOCUMENT_12                    0
FLAG_DOCUMENT_13                    0
FLAG_DOCUMENT_14                    0
FLAG_DOCUMENT_15                    0
FLAG_DOCUMENT_16                    0
FLAG_DOCUMENT_17                    0
FLAG_DOCUMENT_18                    0
FLAG_DOCUMENT_19                    0
FLAG_DOCUMENT_20                    0
FLAG_DOCUMENT_21                    0
AMT_REQ_CREDIT_BUREAU_HOUR       8756
AMT_REQ_CREDIT_BUREAU_DAY        8756
AMT_REQ_CREDIT_BUREAU_WEEK       8756
AMT_REQ_CREDIT_BUREAU_MON        8756
AMT_REQ_CREDIT_BUREAU_QRT        8756
AMT_REQ_CREDIT_BUREAU_YEAR       8756
dtype: int64

In [60]:
test_n=test_n.fillna(test_n.mean().iloc[0])
test_n.isna().sum()[50:]

ENTRANCES_MODE                  0
FLOORSMAX_MODE                  0
FLOORSMIN_MODE                  0
LANDAREA_MODE                   0
LIVINGAPARTMENTS_MODE           0
LIVINGAREA_MODE                 0
NONLIVINGAPARTMENTS_MODE        0
NONLIVINGAREA_MODE              0
APARTMENTS_MEDI                 0
BASEMENTAREA_MEDI               0
YEARS_BEGINEXPLUATATION_MEDI    0
YEARS_BUILD_MEDI                0
COMMONAREA_MEDI                 0
ELEVATORS_MEDI                  0
ENTRANCES_MEDI                  0
FLOORSMAX_MEDI                  0
FLOORSMIN_MEDI                  0
LANDAREA_MEDI                   0
LIVINGAPARTMENTS_MEDI           0
LIVINGAREA_MEDI                 0
NONLIVINGAPARTMENTS_MEDI        0
NONLIVINGAREA_MEDI              0
TOTALAREA_MODE                  0
OBS_30_CNT_SOCIAL_CIRCLE        0
DEF_30_CNT_SOCIAL_CIRCLE        0
OBS_60_CNT_SOCIAL_CIRCLE        0
DEF_60_CNT_SOCIAL_CIRCLE        0
DAYS_LAST_PHONE_CHANGE          0
FLAG_DOCUMENT_2                 0
FLAG_DOCUMENT_3                 0
FLAG_DOCUMENT_4                 0
FLAG_DOCUMENT_5                 0
FLAG_DOCUMENT_6                 0
FLAG_DOCUMENT_7                 0
FLAG_DOCUMENT_8                 0
FLAG_DOCUMENT_9                 0
FLAG_DOCUMENT_10                0
FLAG_DOCUMENT_11                0
FLAG_DOCUMENT_12                0
FLAG_DOCUMENT_13                0
FLAG_DOCUMENT_14                0
FLAG_DOCUMENT_15                0
FLAG_DOCUMENT_16                0
FLAG_DOCUMENT_17                0
FLAG_DOCUMENT_18                0
FLAG_DOCUMENT_19                0
FLAG_DOCUMENT_20                0
FLAG_DOCUMENT_21                0
AMT_REQ_CREDIT_BUREAU_HOUR      0
AMT_REQ_CREDIT_BUREAU_DAY       0
AMT_REQ_CREDIT_BUREAU_WEEK      0
AMT_REQ_CREDIT_BUREAU_MON       0
AMT_REQ_CREDIT_BUREAU_QRT       0
AMT_REQ_CREDIT_BUREAU_YEAR      0
dtype: int64

In [61]:
test_n.isna().sum()[:50]

CNT_CHILDREN                    0
AMT_INCOME_TOTAL                0
AMT_CREDIT                      0
AMT_ANNUITY                     0
AMT_GOODS_PRICE                 0
REGION_POPULATION_RELATIVE      0
DAYS_BIRTH                      0
DAYS_EMPLOYED                   0
DAYS_REGISTRATION               0
DAYS_ID_PUBLISH                 0
OWN_CAR_AGE                     0
FLAG_MOBIL                      0
FLAG_EMP_PHONE                  0
FLAG_WORK_PHONE                 0
FLAG_CONT_MOBILE                0
FLAG_PHONE                      0
FLAG_EMAIL                      0
CNT_FAM_MEMBERS                 0
REGION_RATING_CLIENT            0
REGION_RATING_CLIENT_W_CITY     0
HOUR_APPR_PROCESS_START         0
REG_REGION_NOT_LIVE_REGION      0
REG_REGION_NOT_WORK_REGION      0
LIVE_REGION_NOT_WORK_REGION     0
REG_CITY_NOT_LIVE_CITY          0
REG_CITY_NOT_WORK_CITY          0
LIVE_CITY_NOT_WORK_CITY         0
EXT_SOURCE_1                    0
EXT_SOURCE_2                    0
EXT_SOURCE_3                    0
APARTMENTS_AVG                  0
BASEMENTAREA_AVG                0
YEARS_BEGINEXPLUATATION_AVG     0
YEARS_BUILD_AVG                 0
COMMONAREA_AVG                  0
ELEVATORS_AVG                   0
ENTRANCES_AVG                   0
FLOORSMAX_AVG                   0
FLOORSMIN_AVG                   0
LANDAREA_AVG                    0
LIVINGAPARTMENTS_AVG            0
LIVINGAREA_AVG                  0
NONLIVINGAPARTMENTS_AVG         0
NONLIVINGAREA_AVG               0
APARTMENTS_MODE                 0
BASEMENTAREA_MODE               0
YEARS_BEGINEXPLUATATION_MODE    0
YEARS_BUILD_MODE                0
COMMONAREA_MODE                 0
ELEVATORS_MODE                  0
dtype: int64

In [62]:
scaler = StandardScaler()
#target = train_n['TARGET']
#train_n= test_n#.drop(columns='TARGET')
test_n[:] = scaler.fit_transform(test_n)
test_c=pd.get_dummies(data=test_c)
test = pd.concat([test_n,test_c], axis=1)
test

test['CODE_GENDER_XNA']=0

test['NAME_INCOME_TYPE_Maternity leave']=0

test['NAME_FAMILY_STATUS_Unknown']=0

#AGREGAR COLUMNAS 'CODE_GENDER_XNA',
# 'NAME_INCOME_TYPE_Maternity leave',
# 'NAME_FAMILY_STATUS_Unknown'

#A TEST

test=test.reindex(sorted(test.columns), axis=1)
test

,AMT_ANNUITY,AMT_CREDIT,AMT_GOODS_PRICE,AMT_INCOME_TOTAL,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_YEAR,...,WEEKDAY_APPR_PROCESS_START_SUNDAY,WEEKDAY_APPR_PROCESS_START_THURSDAY,WEEKDAY_APPR_PROCESS_START_TUESDAY,WEEKDAY_APPR_PROCESS_START_WEDNESDAY,YEARS_BEGINEXPLUATATION_AVG,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_AVG,YEARS_BUILD_MEDI,YEARS_BUILD_MODE
0,-0.635747,-0.645976,-0.663910,0.162293,-0.362294,-0.385567,-0.337818,-0.499373,-0.374863,0.161088,...,0,0,0,1,-1.013930,-1.013651,-1.011530,-0.654846,-0.656912,-0.659534
1,-0.717379,-0.082193,-0.176817,-0.028458,-0.362294,-0.385567,-0.337818,1.253849,-0.374863,0.161088,...,0,0,0,0,-1.013930,-1.013651,-1.011530,-0.654846,-0.656912,-0.659534
2,1.740543,1.055892,0.980029,0.114605,-0.362294,-0.385567,-0.337818,-0.499373,-0.374863,1.811520,...,0,0,1,0,0.971095,0.970814,0.971312,1.123227,1.130803,1.155724
3,0.311368,1.188537,0.980029,-0.171522,-0.362294,-0.385567,-0.337818,-0.499373,-0.374863,-0.939200,...,0,1,0,0,-1.013930,-1.013651,-1.011530,-0.654846,-0.656912,-0.659534
4,-0.972787,-0.817878,-0.846570,-0.190597,-0.362294,-0.385567,-0.337818,-0.499373,-0.374863,-0.389056,...,0,0,1,0,-1.013930,-1.013651,-1.011530,-0.654846,-0.656912,-0.659534
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64573,0.177788,0.519732,0.371163,-0.028458,-0.362294,-0.385567,-0.337818,3.007071,-0.374863,0.161088,...,0,0,0,0,0.981690,0.981406,0.981895,-0.654846,-0.656912,-0.659534
64574,-1.062149,-0.727439,-0.627378,0.782235,-0.362294,-0.385567,-0.337818,-0.499373,3.945774,0.161088,...,0,0,0,1,0.967564,0.967283,0.967784,1.043596,1.052867,1.080130
64575,-0.550714,-0.358982,-0.225526,-0.123834,-0.362294,-0.385567,-0.337818,-0.499373,-0.374863,0.711232,...,0,1,0,0,-1.013930,-1.013651,-1.011530,-0.654846,-0.656912,-0.659534
64576,-0.115962,0.512865,0.200680,-0.123834,-0.362294,-0.385567,-0.337818,1.253849,-0.374863,0.711232,...,0,0,0,0,0.953790,0.953514,0.954026,-0.654846,-0.656912,-0.659534
64577,0.284466,0.101478,-0.237704,0.114605,-0.362294,-0.385567,-0.337818,-0.499373,-0.374863,0.161088,...,0,0,0,0,0.967564,0.967283,0.967784,-0.654846,-0.656912,-0.659534

In [63]:
#clf = LogisticRegression(solver='lbfgs',random_state=0).fit(X_train, y_train)
#clf = LogisticRegression(C=0.001, random_state=0).fit(X,y)
#clf = Perceptron(tol=1e-3,eta0=0.1,random_state=0).fit(X,y)
clf  = Perceptron(tol=1e-5,eta0=0.1,penalty=  'l2',random_state=42).fit(X,y)

pred = clf.predict(test)
pred

array([1, 0, 0, ..., 1, 0, 0], dtype=int64)

In [64]:
pred.tolist()

[1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 ...]

In [65]:
u=np.array(pred.tolist())
np.unique(u)

array([0, 1])

In [66]:
df_sub=df_stest['SK_ID_CURR']

In [67]:
sub=pd.DataFrame(df_sub.tolist(), columns=['Id']) 
sub

           Id
0      251482
1      152322
2      213864
3      149195
4      215443
...       ...
64573  449354
64574  118433
64575  177671
64576  449847
64577  390409

[64578 rows x 1 columns]

In [68]:
sub['Expected']= pred.tolist()

sub.columns=['SK_ID_CURR','TARGET']

In [69]:
sub.to_csv(path+'subpercepl1.csv', encoding='utf-8', index=False)

OSError: Cannot save file into a non-existent directory: 'C:\Users\HP\Desktop\U\2 Semestre 2022\ML\Talleres\ml-fintech'

In [ ]:
df_tcm.isna().sum()